### ISSUE TITLE
text doesn't render? 

### ISSUE THREAD

**Issue by stevel4857** [ngokevin/aframe-entity-generator-component#1]
I added this text to the anchor.html file and it won't render. Now sure what's going on. 

<html>
  <head>
    <meta charset='utf-8'>
    <title>A-Frame Hyper Link Component - Anchors</title>
 <script src="https://aframe.io/releases/0.2.0/aframe.min.js"></script>
  <script src="https://rawgit.com/gasolin/aframe-href-component/master/dist/aframe-href-component.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-entity position="0 1.8 4">
        <a-camera id="camera">
          <a-cursor color="#4CC3D9"></a-cursor>
        </a-camera>
      </a-entity>

     <a-text value="1998" position="0 0 0" scale="2 2 2" color="#000000"></a-text>
      <a-box id="home" position="-2 0 -1" rotation="0 30 0" width="2" depth="2"
             height="2" color="#F16745" roughness="0.8" href="#blue-cube">
        <a-event name="cursor-mouseenter" scale="3 1 1" color="#FFC65D"></a-event>
        <a-event name="cursor-mouseenter" target="#shadow" scale="3 2 2"></a-event>
        <a-event name="cursor-mouseleave" scale="1 1 1" color="#F16745"></a-event>
        <a-event name="cursor-mouseleave" target="#shadow" scale="2 2 2"></a-event>
      </a-box>

    
     <a-sphere id="blue-cube" position="2 0 -5" rotation="30 30 0" radius="2"
                                color="blue" roughness="0.8" href="#red-cube">
       <a-event name="cursor-mouseenter" scale="3 1 1" color="#FFC65D"></a-event>
       <a-event name="cursor-mouseenter" target="#shadow2" scale="3 2 2"></a-event>
       <a-event name="cursor-mouseleave" scale="1 1 1" color="#F16745"></a-event>
       <a-event name="cursor-mouseleave" target="#shadow2" scale="2 2 2"></a-event>
     </a-sphere>

    
     <a-sphere id="red-cube" position="10 0 -15" rotation="30 30 0" radius="2"
                                color="red" roughness="0.8" href="#year-2001">
       <a-event name="cursor-mouseenter" scale="3 1 1" color="#FFC65D"></a-event>
       <a-event name="cursor-mouseenter" target="#shadow3" scale="3 2 2"></a-event>
       <a-event name="cursor-mouseleave" scale="1 1 1" color="#F16745"></a-event>
       <a-event name="cursor-mouseleave" target="#shadow3" scale="2 2 2"></a-event>
     </a-sphere>

    
     <a-sphere id="year-2001" position="15 0 -20" rotation="30 30 0" radius="2"
                                color="green" roughness="0.8" href="#home">
       <a-event name="cursor-mouseenter" scale="3 1 1" color="#FFC65D"></a-event>
       <a-event name="cursor-mouseenter" target="#shadow3" scale="3 2 2"></a-event>
       <a-event name="cursor-mouseleave" scale="1 1 1" color="#F16745"></a-event>
       <a-event name="cursor-mouseleave" target="#shadow3" scale="2 2 2"></a-event>
     </a-sphere>

      <a-sky color="#ECECEC"></a-sky>
 <a-text value="1998" position="0 1 0" scale="2 2 2" color="#000000"></a-text>
    </a-scene>
  </body>
</html>

**Comment by ngokevin** [comment]
This seems filed in the wrong location. This is the `entity-generator` component (which is since moved to `ngokevin/kframe`). The A-Frame version you are using is also a year old, and I don't have context of what the `anchors.html` file is. 

http://stackoverflow.com/questions/tagged/aframe is a good place to get general A-Frame help if you can provide some more information (i.e., complete code).
